version: '3'
services:
  backend:
  image: node:14
  build:
    context: ./backend
    dockerfile: Dockerfile
  ports:
    - "4000:4000"
  depends_on:
    - database

  frontend:
    # Configuración del servicio frontend
  database:
    # Configuración del servicio de la base de datos
